version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      framework:
        patterns: [next, eslint-config-next, react, react-dom]
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
